"""
Problem 1: Choose Your Pokemon
Copy and paste the following function:

def choose_pokemon(my_pokemon):
	for pokemon in my_pokemon:
		print(f"{pokemon} I choose you!")
Call the function so that it prints out the following to the console:

Pikachu I choose you!
Charizard I choose you!
Eevee I choose you!
"""

# def choose_pokemon(my_pokemon):
# 	for pokemon in my_pokemon:
# 		print(f"{pokemon} I choose you!")
# my_pokemon = ["Pikachum", "Charizard", "Eevee"]
# choose_pokemon(my_pokemon)


"""
Problem 2: Rotate Left
Write a function rotate_left() that takes in a string s and an integer n as parameters. 
The function returns a new string with the first n characters moved to the end of 
the string where 1 <= n <= len(str).

def rotate_left(s, n):
    pass
Example Usage:

s = "rotation"
print(rotate_left(s, 2))
Example Output: tationro

✨ AI Hint: String Indexing
💡 What's the difference between strings and lists?

"""
# def rotate_left(s, n):
#     return s[n:] + s[:n]
# s = "rotation"
# print(rotate_left(s, 2))

"""
Problem 3: First Duplicate
Write a function first_repeated_char() that takes in a string s as
a parameter and returns the index of the first repeated character in the string.
Uppercase and lowercase letters are considered different characters,
and the function returns None if there are no repeated characters.

def first_repeated_char(s):
    pass
Example Usage:

s = "hello world"
s2 = "aAbBCC"
s3 = "abcdefg"

print(first_repeated_char(s))
print(first_repeated_char(s2))
print(first_repeated_char(s3))
Example Output:

3
5
None
"""
# def first_repeated_char(s):
#     seen = set()

#     for i,val in enumerate(s):
#         if val in seen:
#             return i
#         seen.add(val)
#     return None
# s = "hello world"
# s2 = "aAbBCC"
# s3 = "abcdefg"
# print(first_repeated_char(s))
# print(first_repeated_char(s2))
# print(first_repeated_char(s3))


"""
Problem 4: Find the Imposter
Write a function find_difference() that takes two strings as parameters. 
The second string is generated by shuffling the first string and adding one more 
letter at a random position. Search for and return the added letter.

def find_difference(s1, s2):
    pass
Example Usage:

s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))
Example Output: e
"""
# def find_difference(s1, s2):
#     dict_1 = {}
#     dict_2 = {}

#     for char in s1:
#         dict_1[char] = dict_1.get(char, 0) + 1
    
#     for char in s2:
#         dict_2[char] = dict_2.get(char, 0) + 1
    
#     for char in dict_2:
#         if dict_2[char] > dict_1.get(char, 0):
#             return char
# s1 = "abcd"
# s2 = "baedc"
# print(find_difference(s1, s2))
    

"""
Problem 5: Longest Substring
Write a function that takes in a string s and returns the length of the longest 
substring without repeating characters.

def length_of_longest_substring(s):
	pass
Example Usage:

s = "abcdeefghhhhh"
count = length_of_longest_substring(s)
print(count)

s2 = "aaaaaaaaaaaaaaa"
count = length_of_longest_substring(s2)
print(count)
Example Output:

5
1
"""
# def length_of_longest_substring(s):
#     max_len = 0
#     left = 0
#     seen = set()

#     for right in range(len(s)):
#         while s[right] in seen:
#             seen.remove(s[left])
#             left += 1
#         seen.add(s[right])
#         max_len = max(max_len, right - left + 1)
#     return max_len
# s = "abcdeefghhhhh"
# count = length_of_longest_substring(s)
# print(count)

# s2 = "aaaaaaaaaaaaaaa"
# count = length_of_longest_substring(s2)
# print(count)


"""
Problem 6: Roman to Integer
Roman Numerals are represented by seven different symbols (I, V, X, L, C, D, and M) 
and have these corresponding values:

I = 1 V = 5
X = 10 L = 50
C = 100 D = 500
M = 1000

For example, 2 is written as II, which is just two ones added together.
12 is written as XII, which is simply X + II.
The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. 
However, the numeral for 4 is not IIII. Instead, the number 4 is written as IV.

Because the I is before the V, we subtract it to equal 4. The same principle applies 
to the number 9, which is written as IX. There are six instances where subtraction is used:

I can be placed before V (5) and X (10) to make 4 and 9
X can be placed before L (50) and C (100) to make 40 and 90
C can be placed before D (500) and M (1000) to make 400 and 900
Write a function roman_to_int() that takes in a string s that makes up a roman numeral. 
The function should return the integer value of s.

def roman_to_int(s):
    pass
Example Usage:

s = "XL"
print(roman_to_int(s))

s2 = "LVIII"
print(roman_to_int(s2))

s3 = "MCMXCIV"
print(roman_to_int(s3))
Example Output:

40
58
1994

"""

def roman_to_int(s):
    dict = {
            "I" : 1, "V" : 5,
            "X" : 10,  "L" : 50,
            "C" : 100, "D" : 500,
            "M" : 1000}
    total = 0

    for i in range(len(s) - 1):
        if dict[s[i]] < dict[s[i+1]]:
            total -= dict[s[i]]
        else:
            total += dict[s[i]]
    total += dict[s[-1]]
    return total
s = "XL"
print(roman_to_int(s))

s2 = "LVIII"
print(roman_to_int(s2))

s3 = "MCMXCIV"
print(roman_to_int(s3))